[plugins.csv]
output_path = "alumet-output.csv"
force_flush = true
append_unit_to_metric_name = true
use_unit_display_name = true
csv_delimiter = ";"
csv_late_delimiter = ";"

[plugins.rapl]
poll_interval = "20s"
flush_interval = "30s"
no_perf_events = false